### ISSUE TITLE
Extend dbForm To Handle JSON

### ISSUE THREAD

**Issue by nicky-johnstone** [qcode-software/qcode-ui#75]
Currently `dbForm` is built to use XML . For migrating mla-erp to the new transaction process `dbForm` needs to be able to handle the [Global JSON Response](https://github.com/qcode-software/qcode-tcl/blob/master/doc/global-json-response.md).

The private function `formActionSuccess` is responsible for parsing the XML and setting up the fields in the form with parsed values.

It looks like there are a couple of ways that this can be implemented:

* Update the private function `formActionSuccess` to take in an argument that specifies the data type (XML or JSON) and parses accordingly.

* Define a new function `formActionSuccessJSON` that deals with the JSON response specifically. `formActionSuccess` would continue to specifically deal with the XML response.

<hr>

`httpPost` in `utils` would also have to be updated as it currently expects the returned data to be XML. Perhaps an argument can be passed in to `httpPost` that specifies the expected return type.

<hr>

From what I can see these are the only dependencies upon XML that would have to be changed.

@bvw How would you like me to proceed with this?

**Comment by bvw** [comment]
Would it be possible to cope with both XML or json by detecting the mime type of the returned payload ?

**Comment by nicky-johnstone** [comment]
Looks like it would be possible via something like:

```javascript
jqXHR.getResponseHeader('Content-Type') === 'application/json'
```

Similarly, if the property `dataType` for an ajax request is not specified then it will guess according to the MIME type and act accordingly so the `dataType` property can just be removed from the function `httpPost`

**Comment by bvw** [comment]
Cool, lets pursue that direction please.

**Comment by nicky-johnstone** [comment]
#82
