### ISSUE TITLE
Makefile - remote permissions

### ISSUE THREAD

**Issue by davidqc** [qcode-software/qcode-ui#85]
The ```make``` is usually run by the dev's normal user right?

Any objections if we change the upload stanza to something like this?

If naviserver going to start delivering gzipped versions of these, the ``` nsd ``` user has to be able to write to these subdirectories. So if it's essential that the file be read-only, we need to make sure everything is owned by ``` nsd ``` and only the files (not the directories) are make readonly).

Anyone foresee problems with this approach? (disclaimer - I've not tested it yet)

```
upload: check-version
	# Upload concatenated CSS and JS files to js.qcode.co.uk
	scp -r $(NAME)-$(VERSION) $(REMOTEHOST):$(REMOTEDIR)/$(NAME)-$(VERSION) 

        # Make sure direcory is owned by nsd
	ssh $(REMOTEHOST) 'chown -R nsd:nsd $(REMOTEDIR)/$(NAME)-$(VERSION)'

	# Change permissions to read only to prevent files being overwritten
	ssh $(REMOTEHOST) 'find $(REMOTEDIR)/$(NAME)-$(VERSION) -type f -exec chmod 444 {} +'
```

**Comment by bvw** [comment]
Yes please :+1:

**Comment by davidqc** [comment]
https://github.com/qcode-software/qcode-ui/pull/86
https://github.com/qcode-software/qcode-muppet/pull/27
