### ISSUE TITLE
Validation reset

### ISSUE THREAD

**Issue by PeterChaplin** [qcode-software/qcode-ui#96]
@bvw , @nicky-johnstone 
Why does the validation plugin reset the form on a successful submit?
Can this be made optional?

**Comment by nicky-johnstone** [comment]
I think the use cases at the time meant it was beneficial to reset the form if everything was valid.

I don't see why it couldn't be made optional. An addition of an option to specify whether or not the form should reset could be added. Something like `reset: true` as the default.

**Comment by nicky-johnstone** [comment]
It's been decided to remove the form reset altogether from the plugin. Version 4.4.3 has been released and is available on the CDN.
